export enum Color {
  RED = 'RED',
  BLACK = 'BLACK'
}

export enum PieceType {
  GENERAL = 'GENERAL',
  GUARD = 'GUARD',
  ROOK = 'ROOK',
  HORSE = 'HORSE',
  CANNON = 'CANNON',
  ELEPHANT = 'ELEPHANT',
  SOLDIER = 'SOLDIER'
}

export enum GameState {
  WAITING_FOR_PLAYER = 'WAITING_FOR_PLAYER',
  IN_PROGRESS = 'IN_PROGRESS',
  CHECKMATE = 'CHECKMATE',
  STALEMATE = 'STALEMATE',
  DRAW = 'DRAW'
}